services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "2342:8000"
    networks:
      - app_network
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:15432/solabs_db
  ollama:
    image: ollama/ollama
    volumes:
      - ./ollama-models:/root/.ollama # caminho absoluto do ollama
      - ./start_ollama.sh:/start_ollama.sh
    ports:
      - 11434:11434
    networks:
      - app_network
    entrypoint: ["/bin/sh", "/start_ollama.sh"]

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solabs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
